
import javax.swing.Action;

/**
 * Clase para la vista que contiene un cuadro de texto donde el jugador puede
 * ingresar elecciones.
 *
 */
public class VistaPlayer extends javax.swing.JPanel {

    /**
     * Creates new form VistaPlayer
     */
    public VistaPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Lee el texto del cuadro de texto.
     *
     * @return El texto del cuadro de texto.
     */
    public String leerEntrada() {
        return jTextField1.getText();
    }

    /**
     * Vacía el cuadro de texto.
     */
    public void limpiar() {
        jTextField1.setText("");
    }

    /**
     * Determina qué acción se realizará cuando el cuadro de texto detecte que
     * el usuario presiona la tecla Intro.
     *
     * @param l La acción que se realizará.
     */
    public void añadeAccion(Action l) {
        jTextField1.addActionListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
